version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./config/elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    volumes:
      - type: bind
        source: ./config/kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      - LOGSPOUT=ignore
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    name: elk
    driver: bridge

volumes:
  elasticsearch:
    name: vl-elastic
    driver: local