micronaut:
  application:
    name: demo-micronaut-elasticsearch
  server:
    port: 8080

elasticsearch.httpHosts: 'http://localhost:9200,http://127.0.0.2:9200'

endpoints:
  health:
    elasticsearch:
      rest:
        high:
          level:
            enabled: true